#6 updates README, more inline with requirements
DD2480-Group26/DD2480-CI pull request #45
Opened 2022-02-11 11:03 UTC by cadye

2022-02-11 12:34 UTC, Lantern004 requested changes
It looks good to me! Just need to add the changes that I added to notification part.

2022-02-11 12:34 UTC, Lantern004 commented on README.md
> +Created an Email class in Java with the package javax.mail. This Email class handles the notifications. For every push, it will send the CI result to every participant in the group project. The CI re
I have also changed the README file so it would be good if you can also add the changed part.

2022-02-11 20:42 UTC, Lantern004 approved these changes
Looks good to me!

2022-02-14 15:10 UTC, YaourtNature83 approved these changes
Good

2022-02-15 11:56 UTC, hemenali11 approved these changes

2022-02-16 14:27 UTC, merged