Solved issue #72, jixed javadoc issues, except for PushTester
DD2480-Group26/DD2480-CI pull request #74
Opened 2022-02-15 16:39 UTC by YaourtNature83

2022-02-15 17:18 UTC, Lantern004 requested changes
Good work with the changes!
maybe we need an JavaDoc for handle. And I found that I missed some Javadoc on my Email functions, sorry for that. It's for all different send functions, could you change that for me?

2022-02-16 10:50 UTC, ElisabethChen commented
will fix the part that I commented and push, since the deadline is near

2022-02-16 10:51 UTC, Lantern004 approved these changes

2022-02-16 12:20 UTC, juliaBystrom approved these changes

2022-02-16 13:03 UTC, merged